### PR TITLE
exclude specific input types from react-a11y-input-elements rule

### LINKED ISSUE #749: Rule `react-a11y-input-elements` incorrectly requiring placeholder for radio, checkbox, and file inputs
### Bug Report

-   **`tslint-microsoft-contrib` version**: 6.0.0
-   **TSLint version**: 5.12.0
-   **TypeScript version**: 3.2.2
-   **Running TSLint via**: CLI

#### TypeScript code being linted

```tsx
<input
    type="checkbox"
    checked={props.isSelected}
    onChange={onChange}
/>
```

with `tslint.json` configuration:

```json

  "extends": [
    "tslint:latest",
    "tslint-microsoft-contrib/recommended_ruleset"
  ],

  "rulesDirectory": [
    "tslint-microsoft-contrib"
  ],

  "rules": {
    "quotemark": [true, "single", "jsx-double"],
  }
}
```

#### Actual behavior

ERROR: 40:17    react-a11y-input-elements  Input elements must include default, place-holding characters if empty

#### Expected behavior

Inputs with type checkbox, radio, and, file should not require a placeholder value.

### PR DESCRIPTION
**Pull request by lizzzp1**
#### PR checklist

-   [x] Addresses an existing issue: fixes #749
-   [ ] New feature, bugfix, or enhancement
    -   [x] Includes tests
-   [ ] Documentation update

#### Overview of change:
Excludes the 3 input types listed in issue from requiring a placeholder.

### CODE REVIEW

File: src/reactA11yInputElementsRule.ts [hunk 1]
```diff
@@ -45,17 +46,34 @@ export class Rule extends Lint.Rules.AbstractRule {
     }
 }
 
+function isExcludedInputType(node: ts.JsxSelfClosingElement): boolean {
+    let isExcludedType = false;
+    node.attributes.properties.forEach(
+        (attribute: ts.JsxAttributeLike): void => {
+            if (attribute.kind === ts.SyntaxKind.JsxAttribute) {
```
Comment (JoshuaKGoldberg) [inline src/reactA11yInputElementsRule.ts]: Use `tsutils.isJsxAttribute` on `attribute` and `tsutils.isStringLiteral` on `attribute.initializer. They return whether a given node is of those types, so you won't have to `<>` cast them later on. Nifty hints to the type system.

File: src/tests/ReactA11yInputElementsRuleTests.ts [hunk 2]
```diff
@@ -20,10 +20,21 @@ describe('reactA11yInputElementsRule', (): void => {
         TestHelper.assertViolations(ruleName, script, []);
     });
 
+    it('should pass on input elements without placeholder of type radio, checkbox, file', (): void => {
```
Comment (JoshuaKGoldberg) [inline src/tests/ReactA11yInputElementsRuleTests.ts]: > should pass

Should fail, right? Looks like your change works (🎉) but the test is failing.

File: src/reactA11yInputElementsRule.ts [hunk 3]
```diff
@@ -45,17 +46,34 @@ export class Rule extends Lint.Rules.AbstractRule {
...
             const tagName = node.tagName.getText();
 
-            if (tagName === 'input') {
+            if (tagName === 'input' && !isExcludedInputType(node)) {
                 const attributes = getJsxAttributesFromJsxElement(node);
                 if (isEmpty(attributes.value) && isEmpty(attributes.placeholder)) {
                     ctx.addFailureAt(node.getStart(), node.getWidth(), MISSING_PLACEHOLDER_INPUT_FAILURE_STRING);
                 }
-            } else if (tagName === 'textarea') {
+            } else if (tagName === 'textarea' && !isExcludedInputType(node)) {
```
[the remark this answers is not in the document]
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: Oh oops! You're right

File: src/reactA11yInputElementsRule.ts [hunk 4]
```diff
@@ -45,17 +46,34 @@ export class Rule extends Lint.Rules.AbstractRule {
     }
 }
 
+function isExcludedInputType(node: ts.JsxSelfClosingElement): boolean {
+    let isExcludedType = false;
+    node.attributes.properties.forEach(
```
[the remark this answers is not in the document]
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: ah, yes. Good point.

File: src/reactA11yInputElementsRule.ts (hunk 1 above)
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: Ah. Thank you! I was digging in the TS source code for these types and couldn't find this one.

File: src/tests/ReactA11yInputElementsRuleTests.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply src/tests/ReactA11yInputElementsRuleTests.ts]: Oh sorry you're right, I had it mixed up. The test is right but the code looks like it has a bug.

File: src/reactA11yInputElementsRule.ts [hunk 5]
```diff
@@ -45,17 +46,34 @@ export class Rule extends Lint.Rules.AbstractRule {
...
+        (attribute: ts.JsxAttributeLike): void => {
+            if (attribute.kind === ts.SyntaxKind.JsxAttribute) {
+                if (attribute.initializer !== undefined && attribute.initializer.kind === ts.SyntaxKind.JsxExpression) {
```
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply src/reactA11yInputElementsRule.ts]: > checking properties

I believe so? It should be picking up any attribute on the element, so you'll want to only look at an attribute if it actually is of name `type`

> `isEmpty`

Yes. If a blank type is provided it should default to text IIRC.

File: src/reactA11yInputElementsRule.ts [hunk 6]
```diff
@@ -45,12 +46,29 @@ export class Rule extends Lint.Rules.AbstractRule {
     }
 }
 
+function isExcludedInputType(node: ts.JsxSelfClosingElement): boolean {
+    let isExcludedType = false;
```
Comment (JoshuaKGoldberg) [inline src/reactA11yInputElementsRule.ts]: Not: since this variable is only ever assigned to once, immediately before a return, let's remove it and directly return `true` or `false`. A little less code.

File: src/tests/ReactA11yInputElementsRuleTests.ts [hunk 7]
```diff
@@ -20,10 +20,21 @@ describe('reactA11yInputElementsRule', (): void => {
...
+        const script: string = `
+            import React = require('react');
```
Comment (JoshuaKGoldberg) [inline src/tests/ReactA11yInputElementsRuleTests.ts]: Could you please also add tests for the case of inputs with attribute names other than `type`? Tests are passing without that check in the rule, so they're missing that case.

Comment (lizzzp1) [reply src/tests/ReactA11yInputElementsRuleTests.ts]: Will do!

File: src/reactA11yInputElementsRule.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: So if it's an excluded type and there is no value attribute provided should it give you a more specific failure string? Right now it appears to give you the same failure error when value or placeholder isn't provided.
`Input elements must include default, place-holding characters if empty` Would this make sense if you don't provide a value?

[the remark this answers is not in the document]
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: Sure, sounds good.

File: src/reactA11yInputElementsRule.ts [hunk 8]
```diff
@@ -47,30 +47,30 @@ export class Rule extends Lint.Rules.AbstractRule {
...
             const tagName = node.tagName.getText();
 
-            if (tagName === 'input' && !isExcludedInputType(node)) {
+            if (tagName === 'input') {
                 const attributes = getJsxAttributesFromJsxElement(node);
-                if (isEmpty(attributes.value) && isEmpty(attributes.placeholder)) {
+                const isExcludedInputTypeValueEmpty = isEmpty(attributes.value) && isExcludedInputType(node);
+                const isPlaceholderEmpty = isEmpty(attributes.placeholder) && !isExcludedInputType(node);
+                if ((isEmpty(attributes.value) && isPlaceholderEmpty) || isExcludedInputTypeValueEmpty) {
                     ctx.addFailureAt(node.getStart(), node.getWidth(), MISSING_PLACEHOLDER_INPUT_FAILURE_STRING);
```
Comment (lizzzp1) [inline src/reactA11yInputElementsRule.ts]: 😬 might this be simplified?

Comment (JoshuaKGoldberg) [reply src/reactA11yInputElementsRule.ts]: A couple things to try:

* Pass `attributes` into `isExcludedInputType.type` so you don't have to call `getJsxAttributesFromJsxElement` each time
* Only make one call to `isExcludedInputType(node)` and store that in a variable, so you don't need to call it twice.

...but the test cases look good, build passes, and this is still a pretty simple rule; I'm fine with merging this in as is & filing a followup issue to look into cleaning it up. 

I'll wait for direction from you if you want to tackle it now - totally up to you! 😊

File: src/reactA11yInputElementsRule.ts [hunk 9]
```diff
@@ -46,10 +46,10 @@ export class Rule extends Lint.Rules.AbstractRule {
     }
 }
 
-function isExcludedInputType(node: ts.JsxSelfClosingElement): boolean {
+function isExcludedInputType(node: ts.JsxSelfClosingElement, attributes: { [propName: string]: ts.JsxAttribute }): boolean {
     for (const attribute of node.attributes.properties) {
```
Comment (lizzzp1) [inline src/reactA11yInputElementsRule.ts]: got this type from below. Let me know if this looks right to you.

File: src/reactA11yInputElementsRule.ts (hunk 8 above)
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: Good call! Dried it up ⬇️

File: src/reactA11yInputElementsRule.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (lizzzp1) [reply src/reactA11yInputElementsRule.ts]: What type of issue does this fall under?
