### PR TITLE
Handle relative paths in exceptions for react-no-dangerous-html rule

### LINKED ISSUE #537: Suppressions for react-no-dangerous-html require absolute path
Suppressions for react-no-dangerous-html only work when the file attribute contains the absolute path to the file.

I believe the problem is line 120 in `src/reactNoDangerousHtmlRule.ts` when the file attribute is compared for equality to a `SourceFile.fileName` which is an absolute path.

### PR DESCRIPTION
**Pull request by kevinwilde**
Fixes #537

### CODE REVIEW

File: src/tests/TestHelper.ts [hunk 1]
```diff
@@ -136,9 +137,9 @@ export module TestHelper {
         } else {
             let filename: string;
             if (inputFileOrScript.indexOf('import React') > -1) {
-                filename = 'file.tsx';
+                filename = path.resolve('file.tsx');
             } else {
-                filename = 'file.ts';
+                filename = path.resolve('file.ts');
```
Comment (kevinwilde) [inline src/tests/TestHelper.ts]: The tests previously just used 'file.ts(x)' as a mock filename. Since `reactNoDangerousHtmlRule` now compares `path.resolve(exception.file)` (which returns an absolute path) to `this.getSourceFile().fileName` (which also returns an absolute path when running tslint on an actual project) we need the tests to provide an absolute path for the filename, as well.

Unfortunately, this means I had to change a lot of test files, so this PR has a lot of line changes.

**Comment by kevinwilde** [comment]
Ah shoot. I guess `SourceFile.fileName` uses `/` on Windows, but `path.resolve(..)` uses `\\`. Need to fix the tests

File: src/tests/TestHelper.ts [hunk 2]
```diff
@@ -136,9 +137,9 @@ export module TestHelper {
         } else {
             let filename: string;
             if (inputFileOrScript.indexOf('import React') > -1) {
-                filename = 'file.tsx';
+                filename = Utils.absolutePath('file.tsx');
             } else {
-                filename = 'file.ts';
+                filename = Utils.absolutePath('file.ts');
```
Comment (kevinwilde) [inline src/tests/TestHelper.ts]: The tests previously just used 'file.ts(x)' as a mock filename. Since `reactNoDangerousHtmlRule` now compares `Utils.absolutePath(exception.file)` to `this.getSourceFile().fileName` (which also returns an absolute path when running tslint on an actual project) we need the tests to provide an absolute path for the filename, as well.

Unfortunately, this means I had to change a lot of test files, so this PR has a lot of line changes.
