### PR TITLE
Fix Alt-text cannot be an image file name #217

### LINKED ISSUE #217: Update react-a11y-img-has-alt - Alt-text cannot be an image file name
Alt-text cannot be an image file name (http://oaa-accessibility.org/wcag20/rule/27/, https://github.com/globant-ui/arialinter/blob/master/lib/rules/textAlternatives.js)

### PR DESCRIPTION
**Pull request by Dgaduin**
Fixes #217, by adding a regex to check for most common file formats in use. 
Can use some feedback on the error text and any additional formats that might have been missed

### CODE REVIEW

File: src/reactA11yImgHasAltRule.ts [hunk 1]
```diff
@@ -114,7 +118,8 @@ class ImgHasAltWalker extends Lint.RuleWalker {
             const allowNonEmptyAltWithRolePresentation: boolean = options.length > 1
                 ? options[1].allowNonEmptyAltWithRolePresentation
                 : false;
-
+            const imageFileNameRegex: RegExp = new RegExp('^.*\\.(jpg|bmp|jpeg|jfif|gif|png|tif|tiff)$', 'i');
```
Comment (JoshuaKGoldberg) [inline src/reactA11yImgHasAltRule.ts]: Seems odd to always recreate the regexp here each time. Could you please move this outside of the class?

Even if the underlying JS engine optimizes it away, it's a bit confusing reading through the code.

**Comment by JoshuaKGoldberg** [comment]
> Can use some feedback on the error text and any additional formats that might have been missed

To be more clear: I think they're good as is.
