### PR TITLE
Avoid exception on re-exports (fixes #664)

### LINKED ISSUE #664: export-name: crashes with "Cannot read property 'elements' of undefined"
### Bug Report
The linting rule **export-name** crashes if there's a file containing only one `export * from './Foobar'`.

-   **`tslint-microsoft-contrib` version**: 6.0.0
-   **TSLint version**: 5.11.0
-   **TypeScript version**: 3.1.6
-   **Running TSLint via**: (pick one) CLI `npx tslint --project .`

#### TypeScript code being linted

```tsx
export * from './ValidationWrapper';

```

with `tslint.json` configuration:

```json
{
  "extends": ["tslint-eaa-contrib"],
  "linterOptions": {
    "exclude": [
      "config/**"
    ]
  }
}

```
(It's basically our own ruleset which enables / disables some rules, including from the tslint-microsoft-contrib package)

#### Actual behavior
```
npx tslint --project .
The 'export-name' rule threw an error in 'c:/Source/react-ocean-forms/src/components/withValidation/ValidationWrapper/index.ts':
TypeError: Cannot read property 'elements' of undefined
    at getExportsFromStatement (c:\Source\react-ocean-forms\node_modules\tslint-microsoft-contrib\exportNameRule.js:97:27)
    at ExportNameWalker.visitSourceFile (c:\Source\react-ocean-forms\node_modules\tslint-microsoft-contrib\exportNameRule.js:112:35)
    at ExportNameWalker.SyntaxWalker.visitNode (c:\Source\react-ocean-forms\node_modules\tslint\lib\language\walker\syntaxWalker.js:482:22)
    at ExportNameWalker.SyntaxWalker.walk (c:\Source\react-ocean-forms\node_modules\tslint\lib\language\walker\syntaxWalker.js:24:14)
    at Rule.AbstractRule.applyWithWalker (c:\Source\react-ocean-forms\node_modules\tslint\lib\language\rule\abstractRule.js:31:16)
    at Rule.apply (c:\Source\react-ocean-forms\node_modules\tslint-microsoft-contrib\exportNameRule.js:27:21)
    at Linter.applyRule (c:\Source\react-ocean-forms\node_modules\tslint\lib\linter.js:197:29)
    at c:\Source\react-ocean-forms\node_modules\tslint\lib\linter.js:139:85
    at Object.flatMap (c:\Source\react-ocean-forms\node_modules\tslint\lib\utils.js:151:29)
    at Linter.getAllFailures (c:\Source\react-ocean-forms\node_modules\tslint\lib\linter.js:139:32)
```

#### Expected behavior
Rule should not crash and no linting issue should be found. 

It seems that the rule crashes if there's an file with only one `export * from './Foobar'`. The crash goes away if I have more than one `export * from './Foo'` per file.

### PR DESCRIPTION
**Pull request by IllusionMH**
#### PR checklist

-   [X] Addresses an existing issue: fixes #664
-   [X] New feature, **bugfix**, or enhancement
    -   [X] Includes tests

#### Overview of change:
Full module re-exports do not have `exportClause` with list of re-exported names. After this change existence of `exportClause` is verified and 

#### Is there anything you'd like reviewers to focus on?
Migration of test for `export-name` rule almost finished in local branch so I've used TSLint test format for this change instead of Mocha tests modification. Has same folder structure and config, but includes only specific test file.

At this point I do not see an easy way to perform same verifications for module which is re-exported in current file. Therefore decided to just ignore full module re-exports (`export * from …`).

Probably this will be possible with (optionally) typed rule, however I'm not sure if TS will provide list of exported names. Should I create new issue to track this improvement?

### CODE REVIEW

File: src/exportNameRule.ts [hunk 1]
```diff
@@ -86,12 +86,16 @@ function isExportStatement(node: ts.Statement): node is ExportStatement {
 function getExportsFromStatement(node: ExportStatement): [string, ts.Node][] {
     if (ts.isExportAssignment(node)) {
         return [[node.expression.getText(), node.expression]];
-    } else {
+    } else if (node.exportClause) {
         const symbolAndNodes: [string, ts.Node][] = [];
-        node.exportClause!.elements.forEach(e => {
```
Comment (JoshuaKGoldberg) [inline src/exportNameRule.ts]: > ```diff
> - !
> + 
> ```

More reinforcement for enabling `no-non-null-assertion` in #491...
